services:
    # La base de données (PostgreSQL)
    db:
        image: postgres:16-alpine
        container_name: progressi_db
        restart: always
        environment:
            POSTGRES_USER: dev_user
            POSTGRES_PASSWORD: dev_password
            POSTGRES_DB: progressi_db
        ports:
            - "5432:5432"
        volumes:
            # Permet de sauvegarder tes données SQL entre deux lancements
            - pg_data:/var/lib/postgresql/data

    # Ton application Next.js
    app:
        image: node:20-alpine
        container_name: progressi_app
        working_dir: /usr/src/app
        # La commande magique : installe les paquets, génère le client Prisma, et lance Next.js
        command: sh -c "npm install && npx prisma generate && npm run dev"
        ports:
            - "3000:3000" # Ton interface Next.js
            - "5555:5555" # Port réservé pour Prisma Studio (interface de gestion de ta BDD)
        volumes:
            # Synchronise ton code local avec le conteneur
            - .:/usr/src/app
            # Isole les dossiers générés pour éviter les conflits Windows/Linux(WSL)
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        environment:
            - NODE_ENV=development
            # L'URL de connexion pour Prisma (le mot "db" correspond au nom du service au-dessus)
            - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/progressi_db?schema=public
        depends_on:
            - db

volumes:
    pg_data:
